name: Build and Push Docker Image to Azure Blob
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read image name from README.md
        id: read_image_name
        run: |
          IMAGE_NAME=$(grep -v '^#' README.md | grep -v '^\s*$' | head -n 1)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Sanitize image name and add timestamp
        run: |
          IMAGE_NAME_SANITIZED=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          TIME_STAMP=$(date -u +"%Y-%m-%d-%H-%M-%S")
          IMAGE_NAME_TAG="${IMAGE_NAME_SANITIZED}:${TIME_STAMP}"
          echo "IMAGE_NAME_TAG=$IMAGE_NAME_TAG" >> $GITHUB_ENV
          echo "Sanitized image with timestamp: $IMAGE_NAME_TAG"
        shell: bash

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME_TAG .
        shell: bash

      - name: Save Docker image to tar
        run: |
          docker save -o "${IMAGE_NAME_TAG}.tar" $IMAGE_NAME_TAG
        shell: bash

      - name: Upload tar to Azure Blob Storage
        uses: azure/storage-blob-upload@v1
        with:
          connection-string: ${{ secrets.AZURE_BLOB_SAS_URL }}  # Use the SAS URL secret
          container-name: docker-images-training
          source: "${IMAGE_NAME_TAG}.tar"
          blob-name: "${IMAGE_NAME_TAG}.tar"
